project_name: kubectl-multi-exec

env:
  - GO111MODULE=on

install:
  - go install

builds:
  - main: cmd/kubectl-multi-exec.go
    binary: kubectl-multi_exec
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
       - amd64

release:
  prerelease: auto
