project_name: kubectl-multi-exec

env:
  - GO111MODULE=on

before:
  hooks:
    - go install

builds:
  - main: cmd/kubectl-multi-exec.go
    binary: kubectl-multi_exec
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: 386
    amd64: x86_64

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

release:
  prerelease: auto
